### ISSUE TITLE
TODO: minor code improvements (pytorch)

### ISSUE THREAD

**Issue by parkseobin** [parkseobin/VDSR-pytorch-tf2#3]
- [x] Correct and fill up README.md.
- [x] Variable naming
  - [x] lr confusion
https://github.com/parkseobin/VDSR-pytorch-tf2/blob/33618eee7e8f0f3142b276671ca120c4249fd92b/pytorch/train.py#L50
https://github.com/parkseobin/VDSR-pytorch-tf2/blob/33618eee7e8f0f3142b276671ca120c4249fd92b/pytorch/train.py#L62

  - [x] etc...
<br>

- [x] Choosing best PSNR
https://github.com/parkseobin/VDSR-pytorch-tf2/blob/33618eee7e8f0f3142b276671ca120c4249fd92b/pytorch/train.py#L55

- [x] Efficient validation code
- [x] Remove unused code in ops.py

- [x] Adding super.init inside dataset?
  > Not needed. (https://pytorch.org/docs/stable/_modules/torch/utils/data/dataset.html#Dataset)
- [x] Implement dataset lazy loading with resizing. And change custom dataset name. 
- [x] Use pytorch native functions for transformation
  > Not recommended (Not convenient for SR task)
- [ ] Handle scale variable. 
- [ ] Test detatch function 
  > https://redstarhong.tistory.com/64

**Comment by parkseobin** [comment]
- Test detatch function 
- Use pytorch functions for transformation
